import type { DrinkType, LegalLimit } from "@/types/calculator";

export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://bac-calculator.com";

export const DRINK_TYPES: DrinkType[] = [
  {
    id: "beer",
    label: "Regular Beer",
    alcoholOz: 0.6,
    description: "12 oz, 5% ABV",
  },
  {
    id: "strong-beer",
    label: "Strong Beer",
    alcoholOz: 0.9,
    description: "12 oz, 7.5% ABV",
  },
  {
    id: "wine",
    label: "Wine",
    alcoholOz: 0.6,
    description: "5 oz, 12% ABV",
  },
  {
    id: "shot",
    label: "Shot / Spirits",
    alcoholOz: 0.6,
    description: "1.5 oz, 40% ABV",
  },
  {
    id: "double",
    label: "Double Shot",
    alcoholOz: 1.2,
    description: "3 oz, 40% ABV",
  },
  {
    id: "cocktail",
    label: "Mixed Cocktail",
    alcoholOz: 0.75,
    description: "Average 1-1.5 oz spirits",
  },
];

export const LEGAL_LIMITS: LegalLimit[] = [
  {
    id: "us",
    country: "United States",
    nativeName: "美国",
    label: "US",
    limitPercent: 0.08,
    notes: "Utah: 0.05%. Zero tolerance under 21.",
  },
  {
    id: "uk-england-wales",
    country: "UK (England & Wales)",
    nativeName: "英国（英格兰和威尔士）",
    label: "UK",
    limitPercent: 0.08,
    notes: "Separate threshold from Scotland.",
  },
  {
    id: "uk-scotland",
    country: "UK (Scotland)",
    nativeName: "英国（苏格兰）",
    label: "UK",
    limitPercent: 0.05,
    notes: "Lower limit than England and Wales.",
  },
  {
    id: "canada",
    country: "Canada",
    nativeName: "加拿大",
    label: "CA",
    limitPercent: 0.08,
    notes: "Warning range starts at 0.05%.",
  },
  {
    id: "australia",
    country: "Australia",
    nativeName: "澳大利亚",
    label: "AU",
    limitPercent: 0.05,
    notes: "0.00% for probationary drivers.",
  },
  {
    id: "germany",
    country: "Germany",
    nativeName: "德国",
    label: "DE",
    limitPercent: 0.05,
    notes: "Lower threshold for some drivers.",
  },
  {
    id: "france",
    country: "France",
    nativeName: "法国",
    label: "FR",
    limitPercent: 0.05,
    notes: "Often stricter for novice drivers.",
  },
  {
    id: "japan",
    country: "Japan",
    nativeName: "日本",
    label: "JP",
    limitPercent: 0.03,
    notes: "Strict enforcement; near zero tolerance.",
  },
  {
    id: "china",
    country: "China",
    nativeName: "中国",
    label: "CN",
    limitPercent: 0.02,
    notes: "Drunk driving threshold is higher, but this is the drink-driving line.",
  },
  {
    id: "sweden",
    country: "Sweden",
    nativeName: "瑞典",
    label: "SE",
    limitPercent: 0.02,
    notes: "Among the strictest in Europe.",
  },
  {
    id: "brazil",
    country: "Brazil",
    nativeName: "巴西",
    label: "BR",
    limitPercent: 0,
    notes: "Zero tolerance policy.",
  },
  {
    id: "hungary",
    country: "Hungary",
    nativeName: "匈牙利",
    label: "HU",
    limitPercent: 0,
    notes: "Zero tolerance policy.",
  },
  {
    id: "czech-republic",
    country: "Czech Republic",
    nativeName: "捷克共和国",
    label: "CZ",
    limitPercent: 0,
    notes: "Zero tolerance policy.",
  },
  {
    id: "india",
    country: "India",
    nativeName: "印度",
    label: "IN",
    limitPercent: 0.03,
    notes: "Threshold varies in enforcement by state, but 0.03% is commonly cited.",
  },
  {
    id: "mexico",
    country: "Mexico",
    nativeName: "墨西哥",
    label: "MX",
    limitPercent: 0.08,
    notes: "Local enforcement can vary.",
  },
  {
    id: "new-zealand",
    country: "New Zealand",
    nativeName: "新西兰",
    label: "NZ",
    limitPercent: 0.05,
    notes: "Lower alcohol-breath limit rules also apply.",
  },
  {
    id: "south-africa",
    country: "South Africa",
    nativeName: "南非",
    label: "ZA",
    limitPercent: 0.05,
    notes: "Professional drivers may face stricter rules.",
  },
  {
    id: "south-korea",
    country: "South Korea",
    nativeName: "韩国",
    label: "KR",
    limitPercent: 0.03,
    notes: "Penalties escalate quickly above the threshold.",
  },
  {
    id: "singapore",
    country: "Singapore",
    nativeName: "新加坡",
    label: "SG",
    limitPercent: 0.08,
    notes: "Severe penalties and strict enforcement.",
  },
  {
    id: "norway",
    country: "Norway",
    nativeName: "挪威",
    label: "NO",
    limitPercent: 0.02,
    notes: "Very strict threshold.",
  },
  {
    id: "poland",
    country: "Poland",
    nativeName: "波兰",
    label: "PL",
    limitPercent: 0.02,
    notes: "Very strict threshold.",
  },
  {
    id: "russia",
    country: "Russia",
    nativeName: "俄罗斯",
    label: "RU",
    limitPercent: 0.035,
    notes: "Often represented as 0.035%.",
  },
];
